using System.Collections.ObjectModel;
using CommunityToolkit.Maui.Storage;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using PhotostaxAiCurator.Domain.Interfaces;
using PhotostaxAiCurator.Domain.Models;

namespace PhotostaxAiCurator.App.ViewModels;

/// <summary>Simple display model for EXIF tag key-value pairs.</summary>
public record ExifTagItem(string Key, string Value);

/// <summary>
/// Unified workspace ViewModel — combines scanning, analysis, review, and write-back
/// into a single master-detail experience.
/// </summary>
public partial class WorkspaceViewModel : ObservableObject
{
    private readonly IPhotostaxAdapter _photostax;
    private readonly IEnrichmentPipeline _pipeline;
    private readonly IReviewQueueService _reviewQueue;
    private readonly List<StackItemViewModel> _allStacks = [];
    private CancellationTokenSource? _analysisCts;
    private ReviewItem? _selectedReviewItem;

    // ── Folder & State ─────────────────────────────────────────────
    [ObservableProperty] private string _folderPath = string.Empty;
    [ObservableProperty] private bool _hasFolderOpen;

    // ── Stack Collection ───────────────────────────────────────────
    public ObservableCollection<StackItemViewModel> FilteredStacks { get; } = [];
    [ObservableProperty] private StackItemViewModel? _selectedStack;
    [ObservableProperty] private bool _hasSelectedStack;

    // ── Stats ──────────────────────────────────────────────────────
    [ObservableProperty] private int _totalCount;
    [ObservableProperty] private int _analyzedCount;
    [ObservableProperty] private int _needsReviewCount;
    [ObservableProperty] private int _approvedCount;
    [ObservableProperty] private int _failedCount;

    // ── Detail Panel — Images ──────────────────────────────────────
    [ObservableProperty] private ImageSource? _frontImageSource;
    [ObservableProperty] private ImageSource? _backImageSource;
    [ObservableProperty] private bool _hasBackImage;

    // ── Detail Panel — AI Results (editable) ───────────────────────
    [ObservableProperty] private bool _hasAiResult;
    [ObservableProperty] private string? _editTitle;
    [ObservableProperty] private string? _editDescription;
    [ObservableProperty] private string? _editDate;
    [ObservableProperty] private string? _editPeople;
    [ObservableProperty] private string? _editPlaces;
    [ObservableProperty] private string? _editEvents;
    [ObservableProperty] private string? _editOcr;
    [ObservableProperty] private double _confidence;
    [ObservableProperty] private string _confidenceText = string.Empty;
    [ObservableProperty] private Color _confidenceBadgeColor = Colors.Gray;
    [ObservableProperty] private string? _reviewReason;
    [ObservableProperty] private bool _hasReviewReason;
    [ObservableProperty] private bool _isNeedsReview;
    public ObservableCollection<ExifTagItem> ExifTags { get; } = [];

    // ── Progress ───────────────────────────────────────────────────
    [ObservableProperty] private bool _isAnalyzing;
    [ObservableProperty] private double _progress;
    [ObservableProperty] private string _progressText = string.Empty;

    // ── Filter ─────────────────────────────────────────────────────
    [ObservableProperty] private string _activeFilter = "All";

    public WorkspaceViewModel(
        IPhotostaxAdapter photostax,
        IEnrichmentPipeline pipeline,
        IReviewQueueService reviewQueue)
    {
        _photostax = photostax;
        _pipeline = pipeline;
        _reviewQueue = reviewQueue;
    }

    // ── Selection changed hook (generated by MVVM Toolkit) ─────────
    partial void OnSelectedStackChanged(StackItemViewModel? value)
    {
        HasSelectedStack = value is not null;
        if (value is not null)
            LoadStackDetail(value);
    }

    // ═══════════════════════════════════════════════════════════════
    // Commands
    // ═══════════════════════════════════════════════════════════════

    [RelayCommand]
    private async Task BrowseFolderAsync()
    {
        try
        {
            var result = await FolderPicker.Default.PickAsync(default);
            if (!result.IsSuccessful) return;

            FolderPath = result.Folder.Path;
            _photostax.Open(FolderPath, recursive: true);
            var stacks = _photostax.Scan();

            _allStacks.Clear();
            foreach (var stack in stacks)
                _allStacks.Add(new StackItemViewModel(stack));

            HasFolderOpen = true;
            SelectedStack = null;
            UpdateStats();
            ApplyFilter();
        }
        catch (Exception ex)
        {
            await Shell.Current.DisplayAlertAsync("Error", $"Failed to open folder: {ex.Message}", "OK");
        }
    }

    [RelayCommand]
    private void SetFilter(string filter)
    {
        ActiveFilter = filter;
        ApplyFilter();
    }

    [RelayCommand]
    private async Task AnalyzeAllAsync()
    {
        if (IsAnalyzing) return;

        var pendingIds = _allStacks
            .Where(s => s.Status == EnrichmentStatus.Pending)
            .Select(s => s.Id)
            .ToList();

        if (pendingIds.Count == 0)
        {
            await Shell.Current.DisplayAlertAsync("Nothing to Analyze", "All stacks have already been analyzed.", "OK");
            return;
        }

        IsAnalyzing = true;
        _analysisCts = new CancellationTokenSource();
        var progress = new Progress<BatchProgress>(OnBatchProgress);

        try
        {
            await _pipeline.RunBatchAsync(progress, _analysisCts.Token);
        }
        catch (OperationCanceledException) { }
        catch (Exception ex)
        {
            await Shell.Current.DisplayAlertAsync("Analysis Error", ex.Message, "OK");
        }
        finally
        {
            IsAnalyzing = false;
            _analysisCts = null;
            RefreshStackStatuses();
            UpdateStats();
            ApplyFilter();

            if (SelectedStack is not null)
                LoadStackDetail(SelectedStack);
        }
    }

    [RelayCommand]
    private async Task AnalyzeSelectedAsync()
    {
        if (SelectedStack is null) return;

        try
        {
            await _pipeline.AnalyzeStackAsync(SelectedStack.Id);
            RefreshStackStatuses();
            UpdateStats();
            ApplyFilter();
            LoadStackDetail(SelectedStack);
        }
        catch (Exception ex)
        {
            await Shell.Current.DisplayAlertAsync("Analysis Error", ex.Message, "OK");
        }
    }

    [RelayCommand]
    private void CancelAnalysis() => _analysisCts?.Cancel();

    [RelayCommand]
    private async Task ApproveAsync()
    {
        if (_selectedReviewItem is null || SelectedStack is null) return;

        _reviewQueue.Approve(_selectedReviewItem.StackId);
        await _pipeline.WriteMetadataAsync(_selectedReviewItem);
        SelectedStack.Status = EnrichmentStatus.Approved;
        UpdateStats();
        MoveToNextReviewItem();
    }

    [RelayCommand]
    private async Task ApproveWithEditsAsync()
    {
        if (_selectedReviewItem is null || SelectedStack is null) return;

        if (EditTitle != _selectedReviewItem.AiResult.Title)
            _selectedReviewItem.UserOverrides["title"] = EditTitle;
        if (EditDescription != _selectedReviewItem.AiResult.Description)
            _selectedReviewItem.UserOverrides["description"] = EditDescription;
        if (EditDate != _selectedReviewItem.AiResult.DateEstimate)
            _selectedReviewItem.UserOverrides["date"] = EditDate;

        _reviewQueue.Approve(_selectedReviewItem.StackId);
        await _pipeline.WriteMetadataAsync(_selectedReviewItem);
        SelectedStack.Status = EnrichmentStatus.Approved;
        UpdateStats();
        MoveToNextReviewItem();
    }

    [RelayCommand]
    private void SkipSelected()
    {
        if (_selectedReviewItem is null || SelectedStack is null) return;
        _reviewQueue.Skip(_selectedReviewItem.StackId);
        SelectedStack.Status = EnrichmentStatus.Skipped;
        UpdateStats();
        MoveToNextReviewItem();
    }

    [RelayCommand]
    private async Task WriteApprovedAsync()
    {
        var approved = _reviewQueue.GetAll()
            .Where(i => i.Status == EnrichmentStatus.Approved)
            .ToList();

        if (approved.Count == 0)
        {
            await Shell.Current.DisplayAlertAsync("Nothing to Write", "No approved items to write.", "OK");
            return;
        }

        foreach (var item in approved)
        {
            await _pipeline.WriteMetadataAsync(item);
            var stack = _allStacks.FirstOrDefault(s => s.Id == item.StackId);
            if (stack is not null) stack.Status = EnrichmentStatus.Written;
        }

        UpdateStats();
        ApplyFilter();
        await Shell.Current.DisplayAlertAsync("Done", $"Wrote metadata for {approved.Count} stacks.", "OK");
    }

    [RelayCommand]
    private async Task OpenSettingsAsync()
    {
        await Shell.Current.GoToAsync("settings");
    }

    // ═══════════════════════════════════════════════════════════════
    // Helpers
    // ═══════════════════════════════════════════════════════════════

    private void OnBatchProgress(BatchProgress p)
    {
        MainThread.BeginInvokeOnMainThread(() =>
        {
            Progress = p.TotalStacks > 0 ? (double)p.Completed / p.TotalStacks : 0;
            ProgressText = $"Analyzing {p.Completed}/{p.TotalStacks} — "
                + $"✅ {p.AutoApproved}  ⚠️ {p.NeedsReview}  ❌ {p.Failed}";

            RefreshStackStatuses();
            UpdateStats();
        });
    }

    private void RefreshStackStatuses()
    {
        var allReviews = _reviewQueue.GetAll();
        foreach (var review in allReviews)
        {
            var stack = _allStacks.FirstOrDefault(s => s.Id == review.StackId);
            if (stack is not null)
                stack.Status = review.Status;
        }
    }

    private void UpdateStats()
    {
        TotalCount = _allStacks.Count;
        AnalyzedCount = _allStacks.Count(s => s.Status != EnrichmentStatus.Pending);
        NeedsReviewCount = _allStacks.Count(s => s.Status == EnrichmentStatus.NeedsReview);
        ApprovedCount = _allStacks.Count(s => s.Status is EnrichmentStatus.Approved or EnrichmentStatus.AutoApproved);
        FailedCount = _allStacks.Count(s => s.Status == EnrichmentStatus.Failed);
    }

    private void ApplyFilter()
    {
        var filtered = ActiveFilter switch
        {
            "Pending" => _allStacks.Where(s => s.Status == EnrichmentStatus.Pending),
            "NeedsReview" => _allStacks.Where(s => s.Status == EnrichmentStatus.NeedsReview),
            "Approved" => _allStacks.Where(s => s.Status is EnrichmentStatus.Approved or EnrichmentStatus.AutoApproved),
            "Failed" => _allStacks.Where(s => s.Status == EnrichmentStatus.Failed),
            _ => _allStacks.AsEnumerable()
        };

        FilteredStacks.Clear();
        foreach (var stack in filtered)
            FilteredStacks.Add(stack);
    }

    private void LoadStackDetail(StackItemViewModel stackVm)
    {
        try
        {
            var stack = _photostax.GetStackWithMetadata(stackVm.Id);

            var imagePath = stack.EnhancedPath ?? stack.OriginalPath;
            FrontImageSource = imagePath is not null ? ImageSource.FromFile(imagePath) : null;
            HasBackImage = stack.BackPath is not null;
            BackImageSource = stack.BackPath is not null ? ImageSource.FromFile(stack.BackPath) : null;

            ExifTags.Clear();
            foreach (var tag in stack.ExifTags)
                ExifTags.Add(new ExifTagItem(tag.Key, tag.Value));

            _selectedReviewItem = _reviewQueue.GetAll().FirstOrDefault(r => r.StackId == stackVm.Id);
            HasAiResult = _selectedReviewItem is not null;
            IsNeedsReview = stackVm.Status == EnrichmentStatus.NeedsReview;

            if (_selectedReviewItem is not null)
            {
                var ai = _selectedReviewItem.AiResult;
                EditTitle = ai.Title;
                EditDescription = ai.Description;
                EditDate = ai.DateEstimate;
                EditPeople = ai.People.Count > 0 ? string.Join(", ", ai.People.Select(p => p.Name ?? p.Description)) : null;
                EditPlaces = ai.Places.Count > 0 ? string.Join(", ", ai.Places) : null;
                EditEvents = ai.Events.Count > 0 ? string.Join(", ", ai.Events) : null;
                EditOcr = ai.OcrBack;
                Confidence = ai.OverallConfidence;
                ConfidenceText = $"{ai.OverallConfidence:P0}";
                ConfidenceBadgeColor = _selectedReviewItem.Confidence switch
                {
                    ConfidenceLevel.High => Colors.Green,
                    ConfidenceLevel.Medium => Colors.Orange,
                    ConfidenceLevel.Low => Colors.Red,
                    _ => Colors.Gray,
                };
                ReviewReason = ai.ReviewReason;
                HasReviewReason = ai.ReviewReason is not null;
            }
            else
            {
                ClearAiFields();
            }
        }
        catch
        {
            FrontImageSource = null;
            BackImageSource = null;
            HasBackImage = false;
            ClearAiFields();
        }
    }

    private void ClearAiFields()
    {
        EditTitle = EditDescription = EditDate = EditPeople = EditPlaces = EditEvents = EditOcr = null;
        Confidence = 0;
        ConfidenceText = string.Empty;
        ConfidenceBadgeColor = Colors.Gray;
        ReviewReason = null;
        HasReviewReason = false;
        IsNeedsReview = false;
    }

    private void MoveToNextReviewItem()
    {
        var next = _allStacks.FirstOrDefault(s =>
            s.Status == EnrichmentStatus.NeedsReview && s != SelectedStack);

        SelectedStack = next;
        ApplyFilter();
    }
}
